version: '3.8'

services:
  unzip-bot:
    build: .
    container_name: telegram-unzip-bot
    restart: unless-stopped
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - SESSION_STRING=${SESSION_STRING}
      - DATABASE_URL=${DATABASE_URL}
      - ADMINS=${ADMINS}
      - FORCE_SUB_CHANNELS=${FORCE_SUB_CHANNELS}
      - PREMIUM_LOGS=${PREMIUM_LOGS}
      - BOT_USERNAME=${BOT_USERNAME}
    volumes:
      - ./downloads:/app/downloads
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
